# Generated by Django 5.0.7 on 2024-08-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('order_type', models.CharField(choices=[('DI', 'Dine-In'), ('TO', 'Takeout'), ('DV', 'Delivery')], max_length=2)),
                ('order_status', models.CharField(choices=[('CR', 'Created'), ('RC', 'Received'), ('IP', 'In Preparation'), ('RP', 'Ready for Pickup'), ('SR', 'Served'), ('RJ', 'Rejected')], default='CR', max_length=2)),
                ('payment_status', models.CharField(choices=[('PN', 'Pending'), ('UP', 'Unpaid'), ('PD', 'Paid'), ('RF', 'Refunded')], default='PN', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('preparation_instructions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('order_type', models.CharField(choices=[('DI', 'Dine-In'), ('TO', 'Takeout'), ('DV', 'Delivery')], max_length=2)),
                ('order_status', models.CharField(choices=[('CR', 'Created'), ('RC', 'Received'), ('IP', 'In Preparation'), ('RP', 'Ready for Pickup'), ('SR', 'Served'), ('RJ', 'Rejected')], default='CR', max_length=2)),
                ('order_item', models.CharField(max_length=255)),
                ('preparation_instructions', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PN', 'Pending'), ('UP', 'Unpaid'), ('PD', 'Paid'), ('RF', 'Refunded')], default='PN', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
